name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.PLAYCO_TOKEN }}

    - name: Setup project
      uses: ./.github/actions/setup

    # Build the project
    - name: Build
      run: npm run dist

    # Publish to NPM
    - name: Publish Latest Release
      run: npm run publish-ci
